with open("Hari_2/file/data.txt", "w") as file:
    file.write("Hello, World!\n")
    file.write("Ini adalah contoh penulisan ke dalam file.\n")
    file.write("Semoga bermanfaat untuk belajar Python!\n")
    file.write("Terima kasih sudah membaca.\n")
    file.write("Selamat belajar dan semangat terus!\n")
    file.write("Python adalah bahasa pemrograman yang menyenangkan.\n")
    file.write("Jangan lupa untuk terus berlatih dan eksplorasi.\n")
    file.write("Sampai jumpa di pembelajaran berikutnya!\n")
    file.write("Semoga hari anda menyenangkan!\n")
    file.write("Terimakasih sudah menggunakan Python untuk belajar.\n")
    file.write("Selamat tinggal dan sampai jumpa lagi!\n")
    file.write("Python adalah alat yang hebat untuk mengembangkan berbagai aplikasi.\n")
    file.write("Jangan ragu untuk mencoba hal-hal baru dengan Python.\n")
    file.write("Semoga sukses dalam perjalanan belajar python anda!\n")
    file.write("Terimasih sudah mencoba contoh penulisan ke dalam file ini.\n")
    file.write("Sampai jumpa di pembelajaran berikutnya, tetap salam semangat belajar python!\n")
    file.write("Semoga hari anda menyenangkan dan penuh dengan pembelajaran yang bermanfaat!\n")
    file.write("Terimakasih sudah menggunakan python untuk belajar, semoga sukses dalam perjalanan belajar python anda!\n")
    file.write("Selamat tinggal dan sampai jumpa lagi, tetap semangat belajar python!\n")
    file.write("Python adalah alat yang hebat untuk mengembangkan berbagai aplikasi, jangan ragu untuk mencoba hal-hal baru dengan python!\n")
    file.write("Semoga sukses dalam perjalan belajar python anda, terimakasih sudah mencoba contoh penulisan ke dalam file ini!\n")
    file.write("Sampai jumpa di pembelajaran berikutnya, tetap salam semangat belajar python!\n")
    file.write("Semoga hari anda menyenangkan dan penuh dengan pemebelajaran yang bermanfaat, terimakasih sudah menggunkan python untuk balajar, semoga sukses dalam perjalanan belajar python anda!\n")
    